Test gha-cicd(1)

diff --git a/.github/workflows/openshift.yml b/.github/workflows/openshift.yml
--- a/.github/workflows/openshift.yml
+++ b/.github/workflows/openshift.yml
@@ -33,10 +33,10 @@ env:
   OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
   OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
   # 🖊️ EDIT to set the kube context's namespace after login. Leave blank to use your user's default namespace.
-  OPENSHIFT_NAMESPACE: ""
+  OPENSHIFT_NAMESPACE: "default"
 
   # 🖊️ EDIT to set a name for your OpenShift app, or a default one will be generated below.
-  APP_NAME: ""
+  APP_NAME: "dotnet-app"
 
   # 🖊️ EDIT with the port your application should be accessible on.
   # If the container image exposes *exactly one* port, this can be left blank.
@@ -45,12 +45,13 @@ env:
 
   # 🖊️ EDIT to change the image registry settings.
   # Registries such as GHCR, Quay.io, and Docker Hub are supported.
-  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
-  IMAGE_REGISTRY_USER: ${{ github.actor }}
-  IMAGE_REGISTRY_PASSWORD: ${{ github.token }}
+  IMAGE_REGISTRY: docker.io
+  IMAGE_REGISTRY_USER: ${{ secrets.DOCKER_USER }}
+  IMAGE_REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+
 
   # 🖊️ EDIT to specify custom tags for the container image, or default tags will be generated below.
-  IMAGE_TAGS: ""
+  IMAGE_TAGS: "v1.0"
 
 on:
   # https://docs.github.com/en/actions/reference/events-that-trigger-workflows
@@ -126,7 +127,7 @@ jobs:
       id: build-image
       uses: redhat-actions/buildah-build@v2
       with:
-        image: ${{ env.APP_NAME }}
+        image: cybernetor066/dotnetimage
         tags: ${{ env.IMAGE_TAGS }}
 
         # If you don't have a Dockerfile/Containerfile, refer to https://github.com/redhat-actions/buildah-build#scratch-build-inputs
@@ -140,7 +141,7 @@ jobs:
       id: push-image
       uses: redhat-actions/push-to-registry@v2
       with:
-        image: ${{ steps.build-image.outputs.image }}
+        image: cybernetor066/dotnetimage
         tags: ${{ steps.build-image.outputs.tags }}
         registry: ${{ env.IMAGE_REGISTRY }}
         username: ${{ env.IMAGE_REGISTRY_USER }}
@@ -153,35 +154,39 @@ jobs:
       with:
         oc: 4
 
-    # https://github.com/redhat-actions/oc-login#readme
-    - name: Log in to OpenShift
-      uses: redhat-actions/oc-login@v1
-      with:
-        openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
-        openshift_token: ${{ env.OPENSHIFT_TOKEN }}
-        insecure_skip_tls_verify: true
-        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
+    # # https://github.com/redhat-actions/oc-login#readme
+    # - name: Log in to OpenShift
+    #   uses: redhat-actions/oc-login@v1
+    #   with:
+    #     openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
+    #     openshift_token: ${{ env.OPENSHIFT_TOKEN }}
+    #     insecure_skip_tls_verify: true
+    #     namespace: ${{ env.OPENSHIFT_NAMESPACE }}
 
-    # This step should create a deployment, service, and route to run your app and expose it to the internet.
-    # https://github.com/redhat-actions/oc-new-app#readme
-    - name: Create and expose app
-      id: deploy-and-expose
-      uses: redhat-actions/oc-new-app@v1
-      with:
-        app_name: ${{ env.APP_NAME }}
-        image: ${{ steps.push-image.outputs.registry-path }}
-        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
-        port: ${{ env.APP_PORT }}
+    # # This step should create a deployment, service, and route to run your app and expose it to the internet.
+    # # https://github.com/redhat-actions/oc-new-app#readme
+    # - name: Create and expose app
+    #   id: deploy-and-expose
+    #   uses: redhat-actions/oc-new-app@v1
+    #   with:
+    #     app_name: ${{ env.APP_NAME }}
+    #     image: ${{ steps.push-image.outputs.registry-path }}
+    #     namespace: ${{ env.OPENSHIFT_NAMESPACE }}
+    #     port: ${{ env.APP_PORT }}
 
-    - name: Print application URL
-      env:
-        ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
-        SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
+    # - name: Print application URL
+    #   env:
+    #     ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
+    #     SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
+    #   run: |
+    #     [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
+    #     echo
+    #     echo "======================== Your application is available at: ========================"
+    #     echo ${{ env.ROUTE }}
+    #     echo "==================================================================================="
+    #     echo
+    #     echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
+
+    - name: Confirm operation status
       run: |
-        [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
-        echo
-        echo "======================== Your application is available at: ========================"
-        echo ${{ env.ROUTE }}
-        echo "==================================================================================="
-        echo
-        echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
+        echo "Operation complete!"
